# Generated by Django 4.0.3 on 2022-03-24 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=200, null=True)),
                ('formName', models.CharField(max_length=200, null=True)),
                ('filename', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileID', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('majorID', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200)),
                ('DateOfBirth', models.CharField(max_length=200, null=True)),
                ('Identity', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('fromDate', models.CharField(max_length=200, null=True)),
                ('toDate', models.CharField(max_length=200, null=True)),
                ('attachment', models.CharField(max_length=200, null=True)),
                ('status', models.IntegerField(default=0)),
                ('wpdf', models.IntegerField(default=0)),
                ('sendmail', models.IntegerField(default=0)),
                ('formType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='type', to='polls.type')),
            ],
        ),
    ]
