# Generated by Django 4.0.3 on 2022-03-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='filename',
        ),
    ]
