# Generated by Django 4.0.3 on 2022-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_type_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
