# Generated by Django 4.0.3 on 2022-03-25 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_info_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
