# Generated by Django 4.0.3 on 2022-03-25 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_info_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='updated_at',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
