# Generated by Django 4.0.3 on 2022-03-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_info_major_delete_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='majorID',
            field=models.IntegerField(null=True),
        ),
    ]
