# Generated by Django 4.0.3 on 2022-03-25 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_info_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='type',
            name='updated_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='info',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='info',
            name='updated_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
