# Generated by Django 4.0.3 on 2022-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_type_created_at_type_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='fullName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
