# Generated by Django 4.0.3 on 2022-03-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_info_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='number',
            new_name='phone',
        ),
    ]
