# Generated by Django 4.0.3 on 2022-07-29 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_info_created_at_alter_info_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='signed_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='info',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='info',
            name='updated_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
