# Generated by Django 4.0.3 on 2022-03-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_number_info_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='birthOfDate',
        ),
        migrations.AddField(
            model_name='info',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
