# Generated by Django 4.0.3 on 2022-03-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_info_birthofdate_info_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
