# Generated by Django 4.0.3 on 2022-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_info_signed_at_alter_info_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='signed_at',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
