# Generated by Django 4.0.3 on 2022-03-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='DateOfBirth',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='fromDate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='toDate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
