# Generated by Django 4.0.3 on 2022-03-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_info_dateofbirth_alter_info_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='wpdf',
            field=models.IntegerField(default=0),
        ),
    ]
