# Generated by Django 4.0.3 on 2022-03-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_info_wpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='sendmail',
            field=models.IntegerField(default=0),
        ),
    ]
